# 15.095 | Homework 3

## Rachit Jain | 959080873

# Question 1

In [23]:
using CSV, Tables, LinearAlgebra, Random, Gurobi, JuMP, DataFrames, Statistics

In [2]:
X_train = CSV.read("./UltimateFinal/Regression/X_train.csv", DataFrame);
X_train = X_train[:, 4:end]

562338×63 DataFrame
    Row │ Arts & Photography  Biographies & Memoirs  Business & Money  Childre ⋯
        │ Float64             Float64                Float64           Float64 ⋯
────────┼───────────────────────────────────────────────────────────────────────
      1 │            0.0                    0.0               0.0              ⋯
      2 │            0.0                    0.0               0.0
      3 │            0.0                    0.0               0.0
      4 │            0.0                    0.0               0.0
      5 │            0.0                    0.0               0.0              ⋯
      6 │            0.0                    0.0               0.0
      7 │            0.0                    0.0               0.0
      8 │            0.0                    0.0               0.0
      9 │            3.33333                4.03846           3.55556          ⋯
     10 │            0.0                    0.0               0.0
     11 │            0.0                    4.09091           4.0
   ⋮    │         ⋮                     ⋮                   ⋮                  ⋱
 562329 │            0.0                    4.75              0.0
 562330 │            0.0                    3.33333           0.0              ⋯
 562331 │            0.0                    4.0               0.0
 562332 │            0.0                    4.0               0.0
 562333 │            0.0                    0.0               0.0
 562334 │            4.0                    4.66667           0.0              ⋯
 562335 │            0.0                    0.0               0.0
 562336 │            0.0                    5.0               4.0
 562337 │            0.0                    4.16667           5.0
 562338 │            0.0                    5.0               0.0              ⋯
                                              60 columns and 562317 rows omitted

In [3]:
X_test = CSV.read("./UltimateFinal/Regression/X_test.csv", DataFrame);
X_test = X_test[:, 4:end]

48899×63 DataFrame
   Row │ Arts & Photography  Biographies & Memoirs  Business & Money  Children ⋯
       │ Float64             Float64                Float64           Float64  ⋯
───────┼────────────────────────────────────────────────────────────────────────
     1 │            0.0                    3.0               0.0               ⋯
     2 │            3.33333                4.4               0.0
     3 │            0.0                    0.0               0.0
     4 │            0.0                    4.0               4.0
     5 │            4.5                    4.16667           4.0               ⋯
     6 │            4.0                    3.6               0.0
     7 │            0.0                    4.21429           3.0
     8 │            4.0                    3.85714           4.0
     9 │            4.0                    4.4               0.0               ⋯
    10 │            0.0                    5.0               0.0
    11 │            0.0                    4.25              0.0
   ⋮   │         ⋮                     ⋮                   ⋮                 ⋮ ⋱
 48890 │            0.0                    0.0               0.0
 48891 │            0.0                    4.0               4.33333           ⋯
 48892 │            0.0                    0.0               0.0
 48893 │            0.0                    3.5               3.0625
 48894 │            0.0                    4.2               4.0
 48895 │            4.5                    4.16667           4.0               ⋯
 48896 │            0.0                    5.0               0.0
 48897 │            4.0                    5.0               0.0
 48898 │            0.0                    0.0               0.0
 48899 │            0.0                    0.0               0.0               ⋯
                                               60 columns and 48878 rows omitted

In [12]:
y_train = CSV.read("./UltimateFinal/Regression/y_train.csv", DataFrame);
y_train = y_train[:, 2]

562338-element Vector{Int64}:
 5
 5
 4
 5
 5
 5
 5
 5
 3
 5
 2
 2
 5
 ⋮
 5
 4
 5
 3
 4
 4
 4
 4
 5
 5
 1
 5

In [11]:
y_test = CSV.read("./UltimateFinal/Regression/y_test.csv", DataFrame);
y_test = y_test[:, 2]

48899-element Vector{Int64}:
 2
 4
 4
 5
 5
 4
 4
 4
 5
 5
 5
 5
 4
 ⋮
 4
 5
 5
 5
 4
 2
 5
 4
 2
 5
 4
 5

## Part A

The Lasso problem is:

$$\min_{\beta} \quad \| y-X\beta\|_2^2 + \lambda \|\beta\|_1.$$

We rewrite the above problem as:
$$\min_{\beta,t,a} \quad t + \rho \sum_{j=1}^p a_j
\quad \text{s.t.} \\
\quad \| y-X\beta\|_2^2 \leq t,\\
\quad \beta_j \leq a_j,\\
\quad -\beta_j \leq a_j.$$

We begin by implementing an optimization formulation for the $\ell_1$-regularized regression (Lasso):

In [13]:
function l1_regression(X, y, lambda; solver_output=0) # any argument after the semi-colon are the ones with default values
    n,p = size(X)
    
    # Build model
    model = Model(Gurobi.Optimizer)
    set_optimizer_attribute(model, "OutputFlag", solver_output) 
    
    # Insert variables
    @variable(model, beta[j=1:p])
    @variable(model, a[j=1:p]>=0)
    @variable(model, t>=0)
    
    #Insert constraints
    @constraint(model,[j=1:p], beta[j]<=a[j])
    @constraint(model,[j=1:p], -beta[j]<=a[j])
    @constraint(model, sum((y[i]-sum(X[i,j]*beta[j] for j=1:p))^2 for i=1:n) <= t)
    
    #Objective
    @objective(model, Min, t + lambda*sum(a[j] for j=1:p))
    
    # Optimize
    optimize!(model)
    
    # Return estimated betas
    return (value.(beta))
end

l1_regression (generic function with 1 method)

In [14]:
function compute_mse(X, y, beta)
    n,p = size(X)
    return sum((X*beta .- y).^2)/n
end

compute_mse (generic function with 1 method)

In [20]:
function compute_mae(X, y, beta)
    n,p = size(X)
    return mean(abs.(X*beta .- y))
end

compute_mae (generic function with 1 method)

In [28]:
function compute_r2(X, y_train, y, beta)
    num = sum((X*beta .- y).^2)
    den = sum((y .- mean(y_train)).^2)
    return 1-(num/den)
end

compute_r2 (generic function with 2 methods)

In [15]:
X_train = Matrix(X_train)
X_test = Matrix(X_test)

48899×63 Matrix{Float64}:
 0.0      3.0      0.0      3.0      …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 3.33333  4.4      0.0      3.92857     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0      0.0      0.0      0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0      4.0      4.0      0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0
 4.5      4.16667  4.0      0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0
 4.0      3.6      0.0      0.0      …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0      4.21429  3.0      5.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0
 4.0      3.85714  4.0      0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0
 4.0      4.4      0.0      0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0      5.0      0.0      0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0      4.25     0.0      0.0      …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0      3.0      0.0      0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0      3.57143  0.0      0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0
 ⋮          

In [16]:
beta_ols = l1_regression(X_train, y_train, 0.25);

Set parameter Username
Academic license - for non-commercial use only - expires 2023-08-18


### In-Sample Metrics

In [30]:
is_mse = compute_mse(X_train, y_train, beta_ols)
print("The testing MSE is: ", is_mse)

The testing MSE is: 0.8261465169766279

In [31]:
is_mae = compute_mae(X_train, y_train, beta_ols)
print("The testing MAE is: ", is_mae)

The testing MAE is: 0.7094839546349411

In [32]:
is_r2 = compute_r2(X_train, y_train, y_train, beta_ols)
print("The testing R^2 is: ", is_r2)

The testing R^2 is: 0.09288076300320558

### Out-Of-Sample Metrics

In [21]:
oos_mse = compute_mse(X_test, y_test, beta_ols)
print("The testing MSE is: ", oos_mse)

The testing MSE is: 0.8342191674984312

In [24]:
oos_mae = compute_mae(X_test, y_test, beta_ols)
print("The testing MAE is: ", oos_mae)

The testing MAE is: 0.7116342820328428

In [29]:
oos_r2 = compute_r2(X_test, y_train, y_test, beta_ols)
print("The testing R^2 is: ", oos_r2)

The testing R^2 is: 0.09017482222933826

## Holistic Regression

In [35]:
corr_matrix = cor(X_train);

In [36]:
## Let us find the features that have a correlation of less than 0.5 or greater than -0.5. 
## This limits us to features that have low correlation.
corr_matrix_5 = (corr_matrix .<= 0.5) .& (corr_matrix .>= -0.5)
# corr_matrix_5 = LowerTriangular(corr_matrix_5) - Diagonal(corr_matrix_5)

63×63 BitMatrix:
 0  1  1  1  1  1  1  1  1  1  1  1  1  …  1  1  1  1  1  1  1  1  1  1  1  1
 1  0  1  1  1  1  1  1  1  1  1  1  0     1  1  1  1  1  1  1  1  1  1  1  1
 1  1  0  1  1  1  1  1  1  1  1  1  1     1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  0  1  1  1  1  1  1  1  1  1     1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  0  1  1  1  1  1  1  1  1     1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  0  1  1  1  1  1  1  1  …  1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  0  1  1  1  1  1  1     1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  0  1  1  1  1  1     1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  0  1  1  1  1     1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  0  1  1  1     1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1  0  1  1  …  1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  1  1  0  1     1  1  1  1  1  1  1  1  1  1  1  1
 1  0  1  1  1  1  1  1  1  1  1  1  0     1  1

### Creating additional features

In [38]:
function create_features(X)
    
    ## Define constants
    n = size(X)[1]
    p = size(X)[2]
    
    ## Create an empty matrix with the necessary size to accomodate new features.
    X_new = zeros(n, 3*p);
    
    ## Creating additional features.
    for j in 1:p
        X_new[:, 3*(j-1) + 1] = X[:, j]
        X_new[:, 3*(j-1) + 2] = X[:, j].^2
        X_new[:, 3*(j-1) + 3] = abs.(X[:, j]).^0.5
    end
    
    return X_new
end

create_features (generic function with 1 method)

In [39]:
## Creating the modified X matrices.
X_train_new = create_features(X_train);
X_test_new = create_features(X_test);

In [40]:
## Sanity Check.
size(X_train_new)

(562338, 189)

### Create HC (Set of Highly Correlated Features)

In [41]:
corr_matrix = cor(X_train_new)
corr_matrix = (corr_matrix .>= 0.5) .| (corr_matrix .<= -0.5)
corr_matrix = LowerTriangular(corr_matrix) - Diagonal(corr_matrix)

189×189 LowerTriangular{Int64, Matrix{Int64}}:
 0  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  …  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 1  0  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅     ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 1  1  0  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅     ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 0  0  0  0  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅     ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 0  0  0  1  0  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅     ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 0  0  0  1  1  0  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  …  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 0  0  0  0  0  0  0  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅     ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 0  0  0  0  0  0  1  0  ⋅  ⋅  ⋅  ⋅  ⋅     ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 0  0  0  0  0  0  1  1  0  ⋅  ⋅  ⋅  ⋅     ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 0  0  0  0  0  0  0  0  0  0  ⋅  ⋅  ⋅     ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 0  0  0  0  0  0  0  0  0  1  0  ⋅  ⋅  …  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 0  0  0  0  0  0  0  0  0  1  1  0  ⋅     ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 0  0  0  0  0  0

In [42]:
## Number of pairs of highly correlated features
sum(corr_matrix)

216

### Create Holistic Regression Model

In [60]:
function holistic_regression(X, y, lambda; solver_output=0) # any argument after the semi-colon are the ones with default values

    ## Instantiating new variables.
    n, p_new = size(X)
    p = round(Int, p_new/3) # Making it an integer is essential.
    M = 50
    
    corr_matrix = cor(X)
    corr_matrix = (corr_matrix .>= 0.5) .| (corr_matrix .<= -0.5)
    corr_matrix = LowerTriangular(corr_matrix) - Diagonal(corr_matrix)
    
    corr_features_5 = sort(Tuple.(findall(>(0), corr_matrix)))
    HC_size = size(corr_features_5)[1]
    
    # Build model
    model = Model(Gurobi.Optimizer)
    set_optimizer_attribute(model, "OutputFlag", solver_output) 
    
    
    # Insert Variables.
    @variable(model, beta[j=1:p_new])
    @variable(model, a[j=1:p_new]>=0)
    @variable(model, t>=0)
    @variable(model, z[1:p_new], Bin)
    
    
    # Old Constraints.
    @constraint(model, [j=1:p], beta[j]<=a[j])
    @constraint(model, [j=1:p], -beta[j]<=a[j])
    @constraint(model, sum((y[i]-sum(X[i,j]*beta[j] for j=1:p_new))^2 for i=1:n) <= t)
    
    # New Constraints.
    @constraint(model, [j=1:p_new], -M*z[j] <= beta[j])
    @constraint(model, [j=1:p_new], beta[j] <= M*z[j])
    @constraint(model, sum(z[j] for j=1:p_new) <= 30)
    @constraint(model, [j=1:p], sum(z[i] for i=(3*(j-1)+1):(3*(j-1)+3)) <= 1)
    @constraint(model, [j=1:HC_size], sum(z[corr_features_5[j][i]] for i=1:2) <= 1)

    
    #Objective
    @objective(model, Min, t + lambda*sum(a[j] for j=1:p))
    
    # Optimize
    optimize!(model)
    
    # Return estimated betas
    return (value.(beta))

end

holistic_regression (generic function with 1 method)

In [61]:
beta_holistic = holistic_regression(X_train, y_train, 0.25);

Set parameter Username
Academic license - for non-commercial use only - expires 2023-08-18


We find the number of non-zero values in the resultant beta factor to be 8. This validates that the model ran correctly. Also, all the beta values are not zero which is another validation.

In [62]:
unique(beta_holistic)

16-element Vector{Float64}:
  0.0
  0.3251787299785467
 -0.09711819174844627
  0.06283338450881724
  0.4530664781528831
 -4.2747174390466335e-7
  0.8417127463335456
  5.32671406173109
  3.0961652540593545
 -4.4730249175299415
  6.116909237869239
  1.3665486306152383
  2.132689441522278
  3.26889511158588
  0.03068350269073564
 11.337106860459684

### In-Sample Metrics

In [63]:
is_mse = compute_mse(X_train, y_train, beta_holistic)
print("The testing MSE is: ", is_mse)

The testing MSE is: 5.169877084890784

In [64]:
is_mae = compute_mae(X_train, y_train, beta_holistic)
print("The testing MAE is: ", is_mae)

The testing MAE is: 1.780248277158238

In [65]:
is_r2 = compute_r2(X_train, y_train, y_train, beta_holistic)
print("The testing R^2 is: ", is_r2)

The testing R^2 is: -4.676589878724882

### Out-Of-Sample Metrics

In [66]:
oos_mse = compute_mse(X_test, y_test, beta_holistic)
print("The testing MSE is: ", oos_mse)

The testing MSE is: 5.173424543525212

In [67]:
oos_mae = compute_mae(X_test, y_test, beta_holistic)
print("The testing MAE is: ", oos_mae)

The testing MAE is: 1.7695749510477459

In [68]:
oos_r2 = compute_r2(X_test, y_train, y_test, beta_holistic)
print("The testing R^2 is: ", oos_r2)

The testing R^2 is: -4.6422965191635726

### Recommendations

In [118]:
books = CSV.read("./UltimateFinal/Books.csv", DataFrame);

In [119]:
X_train_copy = CSV.read("./UltimateFinal/Regression/X_train.csv", DataFrame);
X_test_copy = CSV.read("./UltimateFinal/Regression/X_test.csv", DataFrame);

In [122]:
y_train_pred_ols = X_train*beta_ols
y_train_pred_holistic = X_train*beta_holistic
X_train_copy[:,"regression_predictions"] = y_train_pred_ols
X_train_copy[:,"holistic_predictions"] = y_train_pred_holistic

y_test_pred_ols = X_test*beta_ols
y_test_pred_holistic = X_test*beta_holistic
X_test_copy[:,"regression_predictions"] = y_test_pred_ols
X_test_copy[:,"holistic_predictions"] = y_test_pred_holistic

48899-element Vector{Float64}:
  1.2116710815916356
  2.162121898834308
  3.100895960298091
  1.1463157236813868
  3.0759655909997354
  1.2073353651919216
  2.545125637306036
  0.6843006288202803
  1.5812140281796192
  0.9759766242812724
  2.8644354468399302
  1.153346840633207
  2.510362531274774
  ⋮
  2.666205709365917
  0.9489920409019597
  2.41287506053379
  2.297937009073404
  3.5200630838368845
  2.2065171059930195
  3.799793503721421
  3.5996345375261205
  0.7961048233113072
  1.31133275322081
 -2.855112858161844
  1.6698463971767321

In [123]:
X_copy = [X_train_copy; X_test_copy]

611237×68 DataFrame
    Row │ Column1  User   Item   Arts & Photography  Biographies & Memoirs  Bu ⋯
        │ Int64    Int64  Int64  Float64             Float64                Fl ⋯
────────┼───────────────────────────────────────────────────────────────────────
      1 │       0      1  22721             0.0                    0.0         ⋯
      2 │       1      2  15742             0.0                    0.0
      3 │       2      3  20373             0.0                    0.0
      4 │       3      4  15233             0.0                    0.0
      5 │       4      5   1644             0.0                    0.0         ⋯
      6 │       5      6  20734             0.0                    0.0
      7 │       6      7  20608             0.0                    0.0
      8 │       7      8  10625             0.0                    0.0
      9 │       8      9  21522             3.33333                4.03846     ⋯
     10 │       9     10  10535             0.0                    0.0
     11 │      10     11  14247             0.0                    4.09091
   ⋮    │    ⋮       ⋮      ⋮            ⋮                     ⋮               ⋱
 611228 │   48889   5923  23118             0.0                    0.0
 611229 │   48890  10088  23120             0.0                    4.0         ⋯
 611230 │   48891   5163  23121             0.0                    0.0
 611231 │   48892   4211  23122             0.0                    3.5
 611232 │   48893   4319  23122             0.0                    4.2
 611233 │   48894   4779  23122             4.5                    4.16667     ⋯
 611234 │   48895   9985  23124             0.0                    5.0
 611235 │   48896   6412  23124             4.0                    5.0
 611236 │   48897   1446  23126             0.0                    0.0
 611237 │   48898   2025  23128             0.0                    0.0         ⋯
                                              63 columns and 611216 rows omitted

### For Regression

In [111]:
user_9512 = filter(:User => n -> n == 9512, X_copy)
top_pred_books_9512 = sort(user_9512, :regression_predictions, rev=true)[1:10,"Item"]
book_recommendations_9512 = filter(row -> row.Item in top_pred_books_9512, books)
# book_recommendations_9512.order=[findfirst(book_recommendations_9512.Item .== x) for x in top_pred_books_9512]
# sort(book_recommendations_9512, :order)
CSV.write("./UltimateFinal/Recommendations/9512/l1_regression.csv", book_recommendations_9512)

"./UltimateFinal/Recommendations/9512/l1_regression.csv"

In [115]:
user_53 = filter(:User => n -> n == 53, X_copy)
top_pred_books_53 = sort(user_53, :regression_predictions, rev=true)[1:10,"Item"]
book_recommendations_53 = filter(row -> row.Item in top_pred_books_53, books)
# book_recommendations_9512.order=[findfirst(book_recommendations_9512.Item .== x) for x in top_pred_books_9512]
# sort(book_recommendations_9512, :order)
CSV.write("./UltimateFinal/Recommendations/53/l1_regression.csv", book_recommendations_53)

"./UltimateFinal/Recommendations/53/l1_regression.csv"

In [124]:
# book_recommendations_53

### For Holistic Regression

In [125]:
user_9512 = filter(:User => n -> n == 9512, X_copy)
top_pred_books_9512 = sort(user_9512, :holistic_predictions, rev=true)[1:10,"Item"]
book_recommendations_9512 = filter(row -> row.Item in top_pred_books_9512, books)
# book_recommendations_9512.order=[findfirst(book_recommendations_9512.Item .== x) for x in top_pred_books_9512]
# sort(book_recommendations_9512, :order)
CSV.write("./UltimateFinal/Recommendations/9512/holistic_regression.csv", book_recommendations_9512)

"./UltimateFinal/Recommendations/9512/holistic_regression.csv"

In [126]:
user_53 = filter(:User => n -> n == 53, X_copy)
top_pred_books_53 = sort(user_53, :holistic_predictions, rev=true)[1:10,"Item"]
book_recommendations_53 = filter(row -> row.Item in top_pred_books_53, books)
# book_recommendations_9512.order=[findfirst(book_recommendations_9512.Item .== x) for x in top_pred_books_9512]
# sort(book_recommendations_9512, :order)
CSV.write("./UltimateFinal/Recommendations/53/holistic_regression.csv", book_recommendations_53)

"./UltimateFinal/Recommendations/53/holistic_regression.csv"

In [128]:
# book_recommendations_53